name: bowenpianoapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  audioplayers: ^0.20.1
  google_fonts: ^2.3.1
  restart_app: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/piano notes_all/
    - assets/piano/



